server:
  port: 3333

spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:31899/lucaticket?
    username: root
    password: bHaaHdacbCGB-GB41g2H-cFDHGbBB63f
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: TRACE

springdoc:
  show-actuator: true