server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: usuario
        uri: lb://usuario/
        predicates:
          - Path=/usuario/** , /swagger-ui/index.html
      - id: evento
        uri: lb://evento/
        predicates:
          - Path=/evento/**
      - id: banco
        uri: lb://pago/
        predicates:
          - Path=/pago/**

      
       
 
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: TRACE