server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: usuario
        uri: lb://usuario/
        predicates:
          - Path=/usuario/**
      - id: evento
        uri: lb://evento/
        predicates:
          - Path=/evento/**
 
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: TRACE